"""Order + Position schemas (Phase 3).

These are the I/O contract for `OrderManager`, `OrderTracker`, and the
upcoming pre-trade validator (Phase 5). Pydantic enforces invariants at
construction so an agent can't, for example, place a buy with negative
volume — the error surfaces at the boundary, not deep in the simulator.

`client_order_id` is generated by the *caller* (UUID), not the broker, so
duplicate-submit protection works the moment the agent issues the request.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

OrderSide = Literal["BUY", "SELL"]
OrderType = Literal["LO", "ATO", "ATC", "MOK", "MAK"]
OrderStatus = Literal["PENDING", "ACCEPTED", "REJECTED", "FILLED", "PARTIALLY_FILLED", "CANCELLED"]


def _new_client_order_id() -> str:
    """Default factory: UUID-4 prefixed with `co_` for log-grep convenience."""
    return f"co_{uuid.uuid4().hex}"


class OrderRequest(BaseModel):
    """Caller-side order request, validated at construction.

    Always carries a `client_order_id` (auto-generated if not supplied) so
    submit calls are idempotent end-to-end. The matching `OrderResponse`
    quotes the same id back; `OrderTracker` rejects duplicates by id.
    """

    model_config = ConfigDict(frozen=True)

    symbol: str = Field(..., min_length=1, max_length=10, description="Equity ticker (e.g. 'HPG').")
    side: OrderSide
    price: float = Field(..., gt=0.0, description="Limit price in VND.")
    volume: int = Field(..., gt=0, description="Number of shares.")
    order_type: OrderType = "LO"
    client_order_id: str = Field(default_factory=_new_client_order_id)


class OrderResponse(BaseModel):
    """Result of submitting an `OrderRequest` (live or simulated)."""

    model_config = ConfigDict(frozen=True)

    client_order_id: str
    broker_order_id: str | None = Field(None, description="ID assigned by TCBS; None for safe-mode mocks.")
    status: OrderStatus
    submitted_at: datetime = Field(default_factory=datetime.utcnow)
    filled_volume: int = 0
    avg_fill_price: float | None = None
    note: str | None = None


class Position(BaseModel):
    """A single equity holding."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    quantity: int = Field(..., ge=0)
    avg_cost: float = Field(..., ge=0.0, description="VWAP of entries, in VND.")
    market_price: float | None = Field(None, ge=0.0, description="Last known mark; None when stale.")

    @property
    def market_value(self) -> float:
        """Mark-to-market value, or 0 when no market price is available."""
        return (self.market_price or 0.0) * self.quantity

    @property
    def unrealized_pnl(self) -> float:
        """Current PnL vs `avg_cost`. Returns 0 when no market price is set."""
        if self.market_price is None:
            return 0.0
        return (self.market_price - self.avg_cost) * self.quantity


class AccountSnapshot(BaseModel):
    """Point-in-time view of the trading account (cash + positions)."""

    model_config = ConfigDict(frozen=True)

    captured_at: datetime = Field(default_factory=datetime.utcnow)
    cash: float = Field(..., ge=0.0, description="Free cash, in VND.")
    locked_cash: float = Field(0.0, ge=0.0, description="Cash earmarked for unfilled buy orders.")
    buying_power: float = Field(..., ge=0.0, description="Effective spendable cash (cash + margin headroom).")
    positions: list[Position] = Field(default_factory=list)
    is_mock: bool = Field(..., description="True when the snapshot came from the in-process simulator, not the broker.")
    last_sync_status: str = Field("Mock", description="Human-readable status from the last sync attempt.")

    @property
    def equity(self) -> float:
        """Total account value: cash + market value of positions."""
        return self.cash + sum(p.market_value for p in self.positions)
