"""Regression seals for every V2 strategy.

For each (strategy, symbol) pair, this test:
    1. Loads the fixture OHLCV CSV from `tests/fixtures/<symbol>.csv`.
    2. Runs the production `IndicatorEngine` + strategy.
    3. Asserts the resulting `signal` column matches the checked-in
       expected output at `tests/fixtures/expected/<label>__<symbol>.csv`.

The expected files were generated by `tests/fixtures/generate_fixtures.py`.
**Re-run that script (and review the diff) only when an intentional
behaviour change has been made.** Otherwise, a failure here means the
strategy or indicator output drifted unexpectedly.

Phase 0 caveat (see plan file): these seals lock in *post-Phase-1*
behaviour. They guard against future regression, not against any
regression Phase 1 may already have introduced.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from trading_on_tcbs_api.stock_system_v2.core.indicator_engine import IndicatorEngine
from trading_on_tcbs_api.stock_system_v2.strategies import (
    CumulativeDropStrategy,
    DipBuyStrategy,
    IntradayDipStrategy,
    RSIDivergenceStrategy,
    RSIStrategy,
    SimpleMAStrategy,
    VolumeBoomStrategy,
)

FIXTURES_DIR = Path(__file__).resolve().parents[1] / "fixtures"
EXPECTED_DIR = FIXTURES_DIR / "expected"

STRATEGY_FACTORIES = {
    "simple_ma": lambda: SimpleMAStrategy(short_window=20, long_window=50),
    "rsi_basic": lambda: RSIStrategy(period=14, is_reversal=False),
    "rsi_reversal": lambda: RSIStrategy(period=14, is_reversal=True),
    "rsi_divergence": lambda: RSIDivergenceStrategy(rsi_period=14, lookback=5, max_bars_between=30),
    "volume_boom": lambda: VolumeBoomStrategy(window=20, threshold_pct=50.0),
    "dip_buy": lambda: DipBuyStrategy(sma_window=20, drop_pct=10.0),
    "cumulative_drop": lambda: CumulativeDropStrategy(days=3, drop_pct=10.0),
    "intraday_dip": lambda: IntradayDipStrategy(lookback_days=60, percentile=75.0),
}

SYMBOLS = ["HPG", "TCB", "FPT"]


def _load_fixture(symbol: str) -> pd.DataFrame:
    path = FIXTURES_DIR / f"{symbol}.csv"
    df = pd.read_csv(path)
    df["time"] = pd.to_datetime(df["time"])
    df["is_partial"] = df["is_partial"].astype(bool)
    return df


def _load_expected(label: str, symbol: str) -> pd.DataFrame:
    path = EXPECTED_DIR / f"{label}__{symbol}.csv"
    df = pd.read_csv(path)
    df["time"] = pd.to_datetime(df["time"])
    df["signal"] = df["signal"].astype(int)
    return df


@pytest.mark.parametrize(
    "label,symbol",
    [(label, sym) for label in STRATEGY_FACTORIES for sym in SYMBOLS],
)
def test_strategy_signal_matches_seal(label: str, symbol: str):
    df = _load_fixture(symbol)
    engine = IndicatorEngine()
    df_with_indicators = engine.append_indicators(df)
    strat = STRATEGY_FACTORIES[label]()
    actual = strat.generate_signals(df_with_indicators.copy())

    expected = _load_expected(label, symbol)

    actual_keep = actual[["time", "signal"]].copy()
    actual_keep["signal"] = actual_keep["signal"].astype(int)
    actual_keep = actual_keep.reset_index(drop=True)

    pd.testing.assert_frame_equal(
        actual_keep.reset_index(drop=True),
        expected.reset_index(drop=True),
        check_dtype=True,
    )
